# 行列演算の基礎

In [3]:
import numpy as np

In [5]:
#ベクトルの定義
np.array([[1], [2], [3]])

array([[1],
       [2],
       [3]])

In [9]:
#行列の定義
X = np.array([[1 , 2], [3, 4]])

In [10]:
#転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [11]:
#逆行列
#linear algebra:線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [13]:
#行列積
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


# よくある間違い

In [18]:
x = np.array([[1, 2, 3]])
Xt = x.T
print(Xt)

[[1]
 [2]
 [3]]


# Numpyでよく使う処理

In [19]:
X = np.array([[2 ,3 , 4], [1, 2, 3]])

In [20]:
print(X)

[[2 3 4]
 [1 2 3]]


In [21]:
X.shape

(2, 3)

In [22]:
row, col = X.shape

In [23]:
row
col

3

In [24]:
for x in X:
    print(x)
    print("--")

[2 3 4]
--
[1 2 3]
--


# 演習問題

In [30]:
X = np.array([[1, 2, 3], [1, 2, 5], [1, 3, 4], [1, 5, 9]])
X

array([[1, 2, 3],
       [1, 2, 5],
       [1, 3, 4],
       [1, 5, 9]])

In [35]:
Yt = np.array([[1, 5, 6, 8]])
Y = Yt.T
Y

array([[1],
       [5],
       [6],
       [8]])

In [37]:
XtX = np.dot(X.T, X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [38]:
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [39]:
XtY = np.dot(X.T, Y)
print(XtY)

[[ 20]
 [ 70]
 [124]]


In [40]:
w = np.dot(XtX_inv, XtY)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnで実装

In [44]:
#重回帰分析のみ読み込み
from sklearn.linear_model import LinearRegression

In [45]:
#モデルの宣言
model = LinearRegression()

In [46]:
#モデルの学習←パラメータの学習
model.fit(X, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [48]:
#調整後のパラメータ
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [49]:
#調整後のパラメータ切片
model.intercept_

array([-0.14285714])

# 手計算したwと同じく切片を同じ行列で計算する場合

In [50]:
model = LinearRegression(fit_intercept = False)#切片を分離して計算しない設定、デフォルトは分離する設定
model.fit(X, Y)
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [52]:
#予測精度←決定係数、0-1の間で1に近いほど精度が高い(厳密にはマイナスもある)
model.score(X, Y)

0.6923076923076923

In [54]:
#予測値の計算
x = np.array([[1, 2, 3]])
y_pred = model.predict(x)
print(y_pred)

[[3.]]
